version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html5
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/pm2.sh
      timeout: 300
      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root
