version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "ecs-task"
        LoadBalancerInfo:
          ContainerName: "simple-html-container"
          ContainerPort: 80

