version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:741448917398:task-definition/ecs-task"
        LoadBalancerInfo:
          ContainerName: "simple-html-container"
          ContainerPort: 80

