version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:481925865845:task-definition/ecs-task:8"
        LoadBalancerInfo:
          ContainerName: "simple-html-container"
          ContainerPort: 80

