export interface MyCommunity {
  communityId: number
  userId: number
  userName: string
  competitionId: number
  competitionName: string
  shortcutName: string
  playerName: string
  emailAddress: string
  ifCommunityManager: any
  ifMember: any
  communityName?: string
  memberPlayerName?: string
  isCommPaymentDone: boolean
  isPaymentDone: boolean
  commType?: string
  accessType?: string
  winnerRuleId?: number
  amount?: number
  active?: boolean
  tokenName?: string
  tokenAddress?: string
  smartContractAddress?: string
  isToken?: boolean
  firstMatchTimestamp?: number
  noOfWinners?: number
  communityUuid?: string
  totalStackAmount?: number
  isAuthenticated: boolean
  isP2PComm: boolean
  isWinner: boolean
  isCompetitionFinished: boolean
  end: string
  start?: string
  firstEventDate: string
  lastEventDate: string
  isClaimedPrice: boolean
}
